# pytest.ini
[pytest]
# Definir el módulo de settings
DJANGO_SETTINGS_MODULE = config.settings

# Directorios donde buscar pruebas
testpaths = apps

# Patrones de descubrimiento de archivos
python_files = tests.py test_*.py *_tests.py

# Marcadores personalizados para segmentar la ejecución
markers =
    slow: pruebas que toman mucho tiempo
    unit: pruebas unitarias
    integration: pruebas de integración
    database: pruebas que requieren base de datos

# Opciones adicionales de pytest
addopts = --tb=short --strict-markers

