# Generated by Django 6.0.2 on 2026-02-26 01:34

import apps.users.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El celular debe inciar con 3', regex='^3\\d{9}$')])),
                ('ciudad', models.CharField(default='Bogotá', max_length=15)),
                ('latitud', models.FloatField(blank=True, help_text='Latitud geográfica. Debe estar entre -90.0 y 90.0', null=True, validators=[django.core.validators.MinValueValidator(-90.0, message='Latitud mínima permitida: -90.0'), django.core.validators.MaxValueValidator(90.0, message='Latitud máxima permitida: 90.0')])),
                ('longitud', models.FloatField(blank=True, help_text='Longitud geográfica. Debe estar entre -180.0 y 180.0', null=True, validators=[django.core.validators.MinValueValidator(-180.0, message='Longitud mínima permitida: -180.0'), django.core.validators.MaxValueValidator(180.0, message='Longitud máxima permitida: 180.0')])),
                ('nombres', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellidos', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria'), ('PPT', 'Permiso por Protección Temporal'), ('SC', 'Salvoconducto'), ('DIE', 'Documento de Identidad Extranjero')], default='CC', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='El número de documento debe tener al menos 5 caracteres')])),
                ('fecha_nacimiento', models.DateField(validators=[apps.users.models.validate_fecha_nacimiento])),
                ('foto_perfil', models.DateField(blank=True, max_length=255, null=True)),
                ('biografia', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'abstract': False,
            },
        ),
    ]
