# Generated by Django 6.0.2 on 2026-03-01 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0003_localidad_centroacopio_localidad_puntoeca_localidad'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.ForeignKey(blank=True, help_text='Referencia a la localidad, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_rel', to='ecas.localidad'),
        ),
    ]
