# Generated by Django 6.0.2 on 2026-03-03 21:18

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecas', '0003_localidad_centroacopio_localidad_puntoeca_localidad'),
        ('users', '0002_usuario_localidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADM', 'Admnisitrador'), ('CIU', 'Ciudadano'), ('GECA', 'Gestor ECA')], default='CIU', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(help_text='Apellidos completos del usuario', max_length=40, validators=[django.core.validators.MinLengthValidator(3, 'Los apellidos deben tener al menos 3 caracteres')], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, help_text='Breve descripción o biografía del usuario', max_length=500, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de teléfono celular (opcional)', max_length=15, null=True, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el usuario se registró', verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, help_text='Correo electrónico que se utilizará para iniciar sesión', max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(help_text='Fecha de nacimiento (formato: AAAA-MM-DD)', validators=[apps.users.models.validate_fecha_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario (opcional)', null=True, upload_to='perfiles/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo. Desmarcar en lugar de eliminar', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al sitio de administración', verbose_name='Es personal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene todos los permisos sin asignarlos explícitamente', verbose_name='Es superusuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora del último inicio de sesión', null=True, verbose_name='Último acceso'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(help_text='Nombres completos del usuario', max_length=30, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres')], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este número de documento.'}, help_text='Número de documento de identidad (único)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='El número de documento debe tener al menos 5 caracteres')], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria'), ('PPT', 'Permiso por Protección Temporal'), ('SC', 'Salvoconducto'), ('DIE', 'Documento de Identidad Extranjero')], default='CC', help_text='Tipo de documento de identidad', max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='users_usuar_email_af433f_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['numero_documento'], name='users_usuar_numero__b2b967_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario'], name='users_usuar_tipo_us_8e6b94_idx'),
        ),
    ]
