# Generated by Django 6.0.2 on 2026-03-02 22:44

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[apps.users.models.validate_fecha_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
    ]
