# Generated by Django 6.0.2 on 2026-03-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_fecha_nacimiento'),
        ('users', '0003_alter_usuario_options_usuario_tipo_usuario_and_more'),
    ]

    operations = [
    ]
