# Generated by Django 6.0.2 on 2026-03-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_descripcion_usuario_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
