# Generated by Django 6.0.2 on 2026-03-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260304_0835'),
        ('users', '0005_remove_usuario_descripcion_remove_usuario_nombre'),
    ]

    operations = [
    ]
