# Generated by Django 6.0.2 on 2026-03-06 15:27

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260306_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (formato: AAAA-MM-DD)', null=True, validators=[apps.users.models.validate_fecha_nacimiento], verbose_name='Fecha de nacimiento'),
        ),
    ]
