# Generated by Django 6.0.2 on 2026-04-05 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de teléfono celular (opcional)', max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(10, message='El número de celular debe tener al menos 10 caracteres')], verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este número de documento.'}, help_text='Número de documento de identidad (único)', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6, message='El número de documento debe tener al menos 6 caracteres')], verbose_name='Número de documento'),
        ),
    ]
