# Generated by Django 6.0.2 on 2026-05-11 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_celular_alter_usuario_numero_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenValidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email para el cual se generó el token (para registros no confirmados)', max_length=254, verbose_name='Email')),
                ('tipo', models.CharField(choices=[('recuperacion', 'Recuperación de Contraseña'), ('verificacion', 'Verificación de Email')], help_text='Tipo de validación que requiere el token', max_length=20, verbose_name='Tipo de Token')),
                ('token', models.CharField(help_text='Código único de 6 dígitos para validación', max_length=8, unique=True, verbose_name='Token')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el token aún es válido', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el token', verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha y hora en que el token expira', verbose_name='Fecha de Expiración')),
                ('intentos_fallidos', models.IntegerField(default=0, help_text='Número de intentos fallidos de validación', verbose_name='Intentos Fallidos')),
                ('fecha_validacion', models.DateTimeField(blank=True, help_text='Fecha y hora en que el token fue validado exitosamente', null=True, verbose_name='Fecha de Validación')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario asociado (puede ser nulo en registros sin confirmar)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens_validacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Validación',
                'verbose_name_plural': 'Tokens de Validación',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['email', 'tipo'], name='users_token_email_d2d23d_idx'), models.Index(fields=['token'], name='users_token_token_d6dd0f_idx'), models.Index(fields=['usuario', 'tipo'], name='users_token_usuario_d25cf5_idx'), models.Index(fields=['activo', 'fecha_expiracion'], name='users_token_activo_c6e9f2_idx')],
            },
        ),
    ]
