# Generated by Django 6.0.2 on 2026-05-27 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_tokenvalidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya existe un usuario con este número de documento.'}, help_text='Número de documento de identidad (único)', max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6, message='El número de documento debe tener al menos 6 caracteres')], verbose_name='Número de documento'),
        ),
    ]
