# Generated by Django 6.0.2 on 2026-06-01 00:56

import apps.core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario (opcional)', null=True, upload_to='perfiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp')), apps.core.upload_validators.MaxFileSizeValidator(2097152, 'La foto de perfil')], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria'), ('PPT', 'Permiso por Protección Temporal'), ('SC', 'Salvoconducto'), ('DIE', 'Documento de Identidad Extranjero')], default='', help_text='Tipo de documento de identidad (opcional)', max_length=3, verbose_name='Tipo de documento'),
        ),
    ]
