# Generated by Django 6.0.3 on 2026-06-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('CIU', 'Ciudadano'), ('GECA', 'Gestor ECA')], default='CIU', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
