# Generated by Django 6.0.2 on 2026-06-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('NIT', 'Número de Identificación Tributaria'), ('PPT', 'Permiso por Protección Temporal'), ('SC', 'Salvoconducto'), ('DIE', 'Documento de Identidad Extranjero')], default='', help_text='Tipo de documento de identidad (opcional)', max_length=3, null=True, verbose_name='Tipo de documento'),
        ),
    ]
