# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tokenvalidacion',
            new_name='users_token_email_71b7f0_idx',
            old_name='users_token_email_d2d23d_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenvalidacion',
            new_name='users_token_token_597d53_idx',
            old_name='users_token_token_d6dd0f_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenvalidacion',
            new_name='users_token_usuario_1dafdc_idx',
            old_name='users_token_usuario_d25cf5_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenvalidacion',
            new_name='users_token_activo_65f09d_idx',
            old_name='users_token_activo_c6e9f2_idx',
        ),
        migrations.AlterModelTable(
            name='tokenvalidacion',
            table='users_token_validacion',
        ),
    ]
