# Generated by Django 6.0.2 on 2026-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_users_token_email_d2d23d_idx_users_token_email_71b7f0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tokenvalidacion',
            name='users_token_activo_65f09d_idx',
        ),
        migrations.RenameField(
            model_name='tokenvalidacion',
            old_name='activo',
            new_name='es_activo',
        ),
        migrations.AddIndex(
            model_name='tokenvalidacion',
            index=models.Index(fields=['es_activo', 'fecha_expiracion'], name='users_token_es_acti_bbc5f7_idx'),
        ),
    ]
