# Generated by Django 6.0.2 on 2026-06-23 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_tokenvalidacion_users_token_activo_65f09d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carga_masiva',
            field=models.BooleanField(default=False, help_text='Indica si este usuario fue creado mediante importación CSV masiva', verbose_name='Carga masiva'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, help_text='Breve descripción o biografía del usuario', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, help_text='Número de teléfono celular (opcional)', max_length=15, validators=[django.core.validators.MinLengthValidator(10, message='El número de celular debe tener al menos 10 caracteres')], verbose_name='Número de celular'),
        ),
    ]
