# Generated by Django 6.0.2 on 2026-06-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_tokenvalidacion_users_token_activo_65f09d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carga_masiva',
            field=models.BooleanField(default=False, help_text='Indica si este usuario fue creado mediante importación CSV masiva', verbose_name='Carga masiva'),
        ),
    ]
