# Generated by Django 6.0.2 on 2026-06-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_usuario_biografia_alter_usuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='completo_tutorial',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya completó el recorrido interactivo', verbose_name='Tutorial completado'),
        ),
    ]
