# Generated by Django 6.0.2 on 2026-02-26 01:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de material',
                'verbose_name_plural': 'Categorías de material',
                'db_table': 'categoria_material',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de material',
                'verbose_name_plural': 'Tipos de material',
                'db_table': 'tipo_material',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('imagen_url', models.URLField(blank=True, verbose_name='Foto material')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.categoriamaterial', verbose_name='Categoría del material')),
                ('tipo', models.ForeignKey(help_text='Tipo al que pertenece el material', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tipomaterial', verbose_name='Tipo del material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, help_text='Capacidad máxima de almacenamiento del material en el inventario', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='La capacidad máxima debe ser mayor a 0')], verbose_name='Capacidad máxima')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('UN', 'Unidad'), ('TON', 'Tonelada'), ('MC', 'Metro cúbico')], help_text='Unidad de medida utilizada para el material (KG, Unidades, Toneladas, etc.)', max_length=4, verbose_name='Unidad de medida')),
                ('stock_actual', models.DecimalField(decimal_places=2, help_text='Cantidad actual disponible del material en inventario', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='El stock actual no puede ser negativo')], verbose_name='Stock actual')),
                ('umbral_alerta', models.SmallIntegerField(help_text='Porcentaje del stock que activará una alerta (0-100%). Debe ser mayor al umbral crítico', validators=[django.core.validators.MinValueValidator(0, message='El umbral de alerta no puede ser menor a 0%'), django.core.validators.MaxValueValidator(100, message='El umbral de alerta no puede ser mayor a 100%')], verbose_name='Umbral de alerta (%)')),
                ('umbral_critico', models.SmallIntegerField(help_text='Porcentaje del stock que activará una alerta crítica (0-100%). Debe ser menor al umbral de alerta', validators=[django.core.validators.MinValueValidator(0, message='El umbral crítico no puede ser menor a 0%'), django.core.validators.MaxValueValidator(100, message='El umbral crítico no puede ser mayor a 100%')], verbose_name='Umbral crítico (%)')),
                ('alerta', models.CharField(choices=[('OK', 'OK'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], default='OK', help_text='Estado actual de alerta del inventario basado en los umbrales configurados', max_length=15, verbose_name='Estado de alerta')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario de compra del material (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='El precio de compra no puede ser negativo')], verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario de venta del material (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='El precio de venta no puede ser negativo')], verbose_name='Precio de venta')),
                ('centro_acopio', models.ForeignKey(blank=True, help_text='Centro de Acopio asociado al inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecas.centroacopio', verbose_name='Centro de Acopio')),
                ('punto_eca', models.ForeignKey(help_text='Punto de Entrega de Cartón y Afines donde se encuentra el inventario', on_delete=django.db.models.deletion.CASCADE, to='ecas.puntoeca', verbose_name='Punto ECA')),
                ('material', models.ForeignKey(help_text='Material asociado a este inventario', on_delete=django.db.models.deletion.CASCADE, to='inventory.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('material', 'punto_eca'), name='unique_material_por_punto_eca')],
            },
        ),
    ]
