# Generated by Django 6.0.2 on 2026-03-08 05:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_material_options_alter_material_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ocupacion_actual',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Cantidad ocupada actualmente del material en el inventario', max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='La ocupación actual no puede ser negativa')], verbose_name='Ocupación actual'),
            preserve_default=False,
        ),
    ]
