# Generated by Django 6.0.2 on 2026-03-08 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventario_ocupacion_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ocupacion_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad ocupada actualmente del material en el inventario', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='La ocupación actual no puede ser negativa')], verbose_name='Ocupación actual'),
        ),
    ]
