# Generated by Django 6.0.3 on 2026-06-07 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_recalcular_alerta_inventarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='umbral_alerta',
            field=models.SmallIntegerField(help_text='Porcentaje de ocupación que activa alerta (0-100%). Debe ser MENOR al umbral crítico', validators=[django.core.validators.MinValueValidator(0, message='El umbral de alerta no puede ser menor a 0%'), django.core.validators.MaxValueValidator(100, message='El umbral de alerta no puede ser mayor a 100%')], verbose_name='Umbral de alerta (%)'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='umbral_critico',
            field=models.SmallIntegerField(help_text='Porcentaje de ocupación que activa estado crítico (0-100%). Debe ser MAYOR al umbral de alerta', validators=[django.core.validators.MinValueValidator(0, message='El umbral crítico no puede ser menor a 0%'), django.core.validators.MaxValueValidator(100, message='El umbral crítico no puede ser mayor a 100%')], verbose_name='Umbral crítico (%)'),
        ),
    ]
