# Generated by Django 6.0.2 on 2026-06-10 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventario_umbral_alerta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriamaterial',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo al que pertenece esta categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tipomaterial', verbose_name='Tipo de material'),
        ),
    ]
