# Generated by Django 6.0.2 on 2026-06-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0014_alter_centroacopio_table_alter_localidad_table_and_more'),
        ('inventory', '0007_categoriamaterial_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamaterial',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo al que pertenece esta categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='inventory.tipomaterial', verbose_name='Tipo de material'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='centro_acopio',
            field=models.ForeignKey(blank=True, help_text='Centro de Acopio asociado al inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='ecas.centroacopio', verbose_name='Centro de Acopio'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='material',
            field=models.ForeignKey(help_text='Material asociado a este inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventory.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='punto_eca',
            field=models.ForeignKey(help_text='Punto de Entrega de Cartón y Afines donde se encuentra el inventario', on_delete=django.db.models.deletion.CASCADE, related_name='inventario_punto', to='ecas.puntoeca', verbose_name='Punto ECA'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría a la que pertenece el material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='inventory.categoriamaterial', verbose_name='Categoría del material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo al que pertenece el material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='inventory.tipomaterial', verbose_name='Tipo del material'),
        ),
        migrations.AlterModelTable(
            name='categoriamaterial',
            table='inv_categoria_material',
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inv_inventario',
        ),
        migrations.AlterModelTable(
            name='material',
            table='inv_material',
        ),
        migrations.AlterModelTable(
            name='tipomaterial',
            table='inv_tipo_material',
        ),
    ]
