# Generated by Django 6.0.2 on 2026-06-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_categoriamaterial_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamaterial',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo al que pertenece el material (se auto-asigna desde la categoría)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='inventory.tipomaterial', verbose_name='Tipo del material'),
        ),
        migrations.AlterField(
            model_name='tipomaterial',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
