# Generated by Django 6.0.2 on 2026-06-21 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_categoriamaterial_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriamaterial',
            name='tipo',
        ),
        migrations.AddField(
            model_name='material',
            name='clasificacion',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar'), ('MANEJO_ESPECIAL', 'Manejo Especial'), ('PELIGROSO', 'Peligroso'), ('HAZMAT', 'HAZMAT')], default='ESTANDAR', help_text='Nivel de riesgo o manejo especial requerido para este material', max_length=20, verbose_name='Clasificación de manejo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Campo deprecado. Usar clasificacion en su lugar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_deprecados', to='inventory.tipomaterial', verbose_name='Tipo del material (deprecado)'),
        ),
    ]
