# Generated by Django 6.0.2 on 2026-06-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_tipomaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamaterial',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
