# Generated by Django 6.0.2 on 2026-07-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_categoriamaterial_descripcion_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoriamaterial',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_categoria_material_nombre'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_material_nombre'),
        ),
    ]
