# Generated by Django 6.0.2 on 2026-07-02 01:05

from django.db import migrations, models


def deduplicar_materiales(apps, schema_editor):
    Material = apps.get_model("inventory", "Material")
    duplicados = (
        Material.objects.values("nombre")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    for entrada in duplicados:
        nombre = entrada["nombre"]
        registros = list(Material.objects.filter(nombre=nombre).order_by("fecha_creacion"))
        primero = registros[0]
        for idx, dup in enumerate(registros[1:], start=2):
            dup.nombre = f"{nombre} (dup {idx})"
            dup.save(update_fields=["nombre"])


def deduplicar_categorias_material(apps, schema_editor):
    CategoriaMaterial = apps.get_model("inventory", "CategoriaMaterial")
    duplicados = (
        CategoriaMaterial.objects.values("nombre")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    for entrada in duplicados:
        nombre = entrada["nombre"]
        registros = list(CategoriaMaterial.objects.filter(nombre=nombre).order_by("fecha_creacion"))
        primero = registros[0]
        for idx, dup in enumerate(registros[1:], start=2):
            dup.nombre = f"{nombre} (dup {idx})"
            dup.save(update_fields=["nombre"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_categoriamaterial_descripcion_and_more'),
    ]

    operations = [
        migrations.RunPython(deduplicar_materiales, migrations.RunPython.noop),
        migrations.RunPython(deduplicar_categorias_material, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='categoriamaterial',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_categoria_material_nombre'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_material_nombre'),
        ),
    ]
