# Generated by Django 6.0.2 on 2026-03-22 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecas', '0007_puntoeca_descripcion'),
        ('inventory', '0004_alter_inventario_ocupacion_actual'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('color', models.CharField(blank=True, max_length=7)),
                ('tipo_repeticion', models.CharField(blank=True, choices=[('NINGUNA', 'Ninguna'), ('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=15, null=True)),
                ('fecha_fin_repeticion', models.DateTimeField(blank=True, null=True)),
                ('es_evento_generado', models.BooleanField(default=False)),
                ('centro_acopio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ecas.centroacopio')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='inventory.material')),
                ('punto_eca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ecas.puntoeca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to=settings.AUTH_USER_MODEL)),
                ('venta_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='operations.ventainventario')),
            ],
            options={
                'db_table': 'evento',
                'abstract': False,
                'unique_together': {('venta_inventario', 'punto_eca')},
            },
        ),
        migrations.CreateModel(
            name='EventoInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('numero_repeticion', models.IntegerField(blank=True, null=True)),
                ('es_completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evento_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='scheduling.evento')),
                ('punto_eca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias_evento', to='ecas.puntoeca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias_evento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
