# Generated by Django 6.0.2 on 2026-03-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='evento',
            name='venta_inventario',
        ),
    ]
