# Generated by Django 6.0.2 on 2026-03-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_evento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventoinstancia',
            table='evento_instancia',
        ),
    ]
