# Generated by Django 6.0.2 on 2026-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_alter_eventoinstancia_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="titulo",
            field=models.CharField(max_length=100),
        ),
    ]