# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_evento_titulo_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventoinstancia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Instancia de evento', 'verbose_name_plural': 'Instancias de evento'},
        ),
        migrations.AlterModelTable(
            name='evento',
            table='age_evento',
        ),
        migrations.AlterModelTable(
            name='eventoinstancia',
            table='age_evento_instancia',
        ),
    ]
