# Generated by Django 6.0.2 on 2026-06-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_evento_options_alter_eventoinstancia_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoinstancia',
            old_name='completado_en',
            new_name='fecha_completado',
        ),
    ]
