# Generated by Django 6.0.2 on 2026-02-26 01:34

import apps.operations.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecas', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_compra', models.DateTimeField(help_text='La fecha de compra es obligatoria y no puede ser futura', validators=[apps.operations.models.validar_fecha_operacion], verbose_name='Fecha de compra')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de material comprado', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser mayor a 0')], verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario de compra del material (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='El precio de compra no puede ser negativo')], verbose_name='Precio de compra')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('inventario', models.ForeignKey(db_column='inventario_id', help_text='Inventario al cual se realiza la compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='inventory.inventario', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Compra de Inventario',
                'verbose_name_plural': 'Compras de Inventario',
                'db_table': 'compra_inventario',
                'ordering': ['-fecha_compra'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VentaInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_venta', models.DateTimeField(help_text='La fecha de venta es obligatoria y no puede ser futura', validators=[apps.operations.models.validar_fecha_operacion], verbose_name='Fecha de venta')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de material vendido', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='La cantidad debe ser mayor a 0')], verbose_name='Cantidad')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario de venta del material (opcional)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0, message='El precio de venta no puede ser negativo')], verbose_name='Precio de venta')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('centro_acopio', models.ForeignKey(blank=True, db_column='centro_acopio_id', help_text='Centro de acopio al cual se vende el material', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ecas.centroacopio', verbose_name='Centro de Acopio')),
                ('inventario', models.ForeignKey(db_column='inventario_id', help_text='Inventario del cual se realiza la venta', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='inventory.inventario', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Venta de Inventario',
                'verbose_name_plural': 'Ventas de Inventario',
                'db_table': 'venta_inventario',
                'ordering': ['-fecha_venta'],
                'abstract': False,
            },
        ),
    ]
