# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_convertir_fechas_naive_a_aware'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comprainventario',
            table='ope_compra_inventario',
        ),
        migrations.AlterModelTable(
            name='ventainventario',
            table='ope_venta_inventario',
        ),
    ]
