# Generated by Django 6.0.2 on 2026-06-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_null_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprainventario',
            name='carga_masiva',
            field=models.BooleanField(default=False, help_text='Indica si este registro fue creado mediante importación CSV masiva', verbose_name='Carga masiva'),
        ),
        migrations.AddField(
            model_name='ventainventario',
            name='carga_masiva',
            field=models.BooleanField(default=False, help_text='Indica si este registro fue creado mediante importación CSV masiva', verbose_name='Carga masiva'),
        ),
    ]
