# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelTable(
            name='dashboard',
            table='adm_tablero',
        ),
        migrations.AlterModelTable(
            name='report',
            table='adm_informe',
        ),
        migrations.AlterModelTable(
            name='widget',
            table='adm_widget',
        ),
    ]
