# Generated by Django 6.0.2 on 2026-06-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0002_alter_dashboard_options_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Tablero', 'verbose_name_plural': 'Tableros'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Informe', 'verbose_name_plural': 'Informes'},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['posicion_y', 'posicion_x'], 'verbose_name': 'Widget', 'verbose_name_plural': 'Widgets'},
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='is_public',
            new_name='es_publico',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='updated_at',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='owner',
            new_name='propietario',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='is_scheduled',
            new_name='es_programado',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='updated_at',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='generated_by',
            new_name='generado_por',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='parameters',
            new_name='parametros',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_type',
            new_name='tipo_informe',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='height',
            new_name='alto',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='width',
            new_name='ancho',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='config',
            new_name='configuracion',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='updated_at',
            new_name='fecha_modificacion',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='position_x',
            new_name='posicion_x',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='position_y',
            new_name='posicion_y',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='widget_type',
            new_name='tipo_widget',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='title',
            new_name='titulo',
        ),
    ]
