# Generated by Django 6.0.2 on 2026-02-26 01:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroAcopio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El celular debe inciar con 3', regex='^3\\d{9}$')])),
                ('ciudad', models.CharField(default='Bogotá', max_length=15)),
                ('latitud', models.FloatField(blank=True, help_text='Latitud geográfica. Debe estar entre -90.0 y 90.0', null=True, validators=[django.core.validators.MinValueValidator(-90.0, message='Latitud mínima permitida: -90.0'), django.core.validators.MaxValueValidator(90.0, message='Latitud máxima permitida: 90.0')])),
                ('longitud', models.FloatField(blank=True, help_text='Longitud geográfica. Debe estar entre -180.0 y 180.0', null=True, validators=[django.core.validators.MinValueValidator(-180.0, message='Longitud mínima permitida: -180.0'), django.core.validators.MaxValueValidator(180.0, message='Longitud máxima permitida: 180.0')])),
                ('sitio_web', models.CharField(blank=True, help_text='URL del sitio web oficial, si aplica.', max_length=255, null=True)),
                ('horario_atencion', models.CharField(blank=True, help_text='Horario de atención al público, ej: L-V 8am-6pm', max_length=100, null=True)),
                ('nombre', models.CharField(help_text='Nombre único identificativo del centro de acopio', max_length=100, unique=True, verbose_name='Nombre del centro de acopio')),
                ('tipo_centro', models.CharField(choices=[('PLANTA', 'Planta'), ('PROVEEDOR', 'Proveedor'), ('OTRO', 'Otro')], default='PLANTA', help_text='Clasificación del centro de acopio', max_length=20, verbose_name='Tipo de centro')),
                ('visibilidad', models.CharField(choices=[('GLOBAL', 'Global'), ('ECA', 'ECA')], default='GLOBAL', help_text='Define quién puede ver este centro de acopio', max_length=20, verbose_name='Nivel de visibilidad')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del centro de acopio', max_length=500, verbose_name='Descripción')),
                ('nota', models.TextField(blank=True, help_text='Información adicional o notas internas', max_length=500, verbose_name='Notas adicionales')),
                ('nombre_contacto', models.CharField(blank=True, help_text='Nombre de la persona de contacto del centro', max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')], verbose_name='Nombre del contacto')),
            ],
            options={
                'verbose_name': 'Centro de Acopio',
                'verbose_name_plural': 'Centros de Acopio',
                'db_table': 'centro_acopio',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoECA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('celular', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El celular debe inciar con 3', regex='^3\\d{9}$')])),
                ('ciudad', models.CharField(default='Bogotá', max_length=15)),
                ('latitud', models.FloatField(blank=True, help_text='Latitud geográfica. Debe estar entre -90.0 y 90.0', null=True, validators=[django.core.validators.MinValueValidator(-90.0, message='Latitud mínima permitida: -90.0'), django.core.validators.MaxValueValidator(90.0, message='Latitud máxima permitida: 90.0')])),
                ('longitud', models.FloatField(blank=True, help_text='Longitud geográfica. Debe estar entre -180.0 y 180.0', null=True, validators=[django.core.validators.MinValueValidator(-180.0, message='Longitud mínima permitida: -180.0'), django.core.validators.MaxValueValidator(180.0, message='Longitud máxima permitida: 180.0')])),
                ('sitio_web', models.CharField(blank=True, help_text='URL del sitio web oficial, si aplica.', max_length=255, null=True)),
                ('horario_atencion', models.CharField(blank=True, help_text='Horario de atención al público, ej: L-V 8am-6pm', max_length=100, null=True)),
                ('telefono_punto', models.CharField(blank=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono fijo debe tener el formato 60 + indicativo + 7 dígitos (ej: 6012345678)', regex='^60\\d{8}')], verbose_name='Teléfono punto')),
                ('direccion', models.CharField(blank=True, max_length=150, verbose_name='Dirección')),
                ('logo_url_punto', models.URLField(blank=True, verbose_name='Logo URL punto')),
                ('foto_url_punto', models.URLField(blank=True, verbose_name='Foto URL punto')),
            ],
            options={
                'verbose_name': 'Punto ECA',
                'verbose_name_plural': 'Puntos ECA',
                'db_table': 'punto_eca',
                'abstract': False,
            },
        ),
    ]
