# Generated by Django 6.0.2 on 2026-02-26 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecas', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoeca',
            name='gestor_eca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_eca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puntoeca',
            name='inventarios',
            field=models.ManyToManyField(blank=True, related_name='puntos_eca_inventario', to='inventory.inventario'),
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='puntos_eca',
            field=models.ManyToManyField(blank=True, help_text='Puntos ECA asociados a este centro de acopio', related_name='centros_acopio', to='ecas.puntoeca', verbose_name='Puntos ECA'),
        ),
    ]
