# Generated by Django 6.0.2 on 2026-03-01 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('localidad_id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='El nombre de la localidad es obligatorio, entre 3 y 30 caracteres.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de la localidad debe tener entre 3 y 30 caracteres.', regex='^.{3,30}$')])),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidad',
                'indexes': [models.Index(fields=['nombre'], name='idx_localidad_nombre')],
            },
        ),
        migrations.AddField(
            model_name='centroacopio',
            name='localidad',
            field=models.ForeignKey(blank=True, help_text='Referencia a la localidad, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_rel', to='ecas.localidad'),
        ),
        migrations.AddField(
            model_name='puntoeca',
            name='localidad',
            field=models.ForeignKey(blank=True, help_text='Referencia a la localidad, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_rel', to='ecas.localidad'),
        ),
    ]
