# Generated by Django 6.0.2 on 2026-03-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0003_localidad_centroacopio_localidad_puntoeca_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoeca',
            name='nombre',
            field=models.CharField(default='Punto ECA Sin Nombre', help_text='Nombre identificativo del punto ECA', max_length=100, verbose_name='Nombre del punto ECA'),
        ),
    ]
