# Generated by Django 6.0.2 on 2026-03-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0004_puntoeca_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoeca',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
