# Generated by Django 6.0.2 on 2026-03-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0005_puntoeca_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoeca',
            name='descripcion',
        ),
    ]
