# Generated by Django 6.0.2 on 2026-03-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0006_remove_puntoeca_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoeca',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción detallada del punto ECA', max_length=500, null=True, verbose_name='Descripción del punto ECA'),
        ),
    ]
