# Generated by Django 6.0.2 on 2026-04-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0008_alter_centroacopio_horario_atencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='remitente',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
