# Generated by Django 6.0.2 on 2026-05-30

from django.db import migrations, models
import apps.core.upload_validators
import config.constants
from django.core.validators import FileExtensionValidator


class Migration(migrations.Migration):

    dependencies = [
        ("ecas", "0009_remove_mensaje_chat_remove_mensaje_remitente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puntoeca",
            name="foto_imagen_punto",
            field=models.ImageField(
                blank=True,
                help_text="Foto principal del punto cargada como archivo (opcional)",
                null=True,
                upload_to="puntos/fotos/",
                validators=[
                    FileExtensionValidator(
                        allowed_extensions=config.constants.IMAGE_UPLOAD_ALLOWED_EXTENSIONS
                    ),
                    apps.core.upload_validators.MaxFileSizeValidator(
                        config.constants.POINT_PHOTO_IMAGE_MAX_SIZE,
                        "La foto del punto",
                    ),
                ],
                verbose_name="Foto del punto",
            ),
        ),
        migrations.AddField(
            model_name="puntoeca",
            name="logo_imagen_punto",
            field=models.ImageField(
                blank=True,
                help_text="Logo del punto cargado como archivo (opcional)",
                null=True,
                upload_to="puntos/logos/",
                validators=[
                    FileExtensionValidator(
                        allowed_extensions=config.constants.IMAGE_UPLOAD_ALLOWED_EXTENSIONS
                    ),
                    apps.core.upload_validators.MaxFileSizeValidator(
                        config.constants.POINT_LOGO_IMAGE_MAX_SIZE,
                        "El logo del punto",
                    ),
                ],
                verbose_name="Logo del punto",
            ),
        ),
    ]