# Generated by Django 6.0.2 on 2026-06-01 00:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0011_puntoeca_visible_en_mapa'),
        ('inventory', '0004_alter_inventario_ocupacion_actual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoeca',
            name='gestor_eca',
            field=models.OneToOneField(blank=True, help_text='Usuario gestor asociado a este punto ECA (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='punto_eca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='puntoeca',
            name='inventarios',
            field=models.ManyToManyField(blank=True, help_text='Inventarios asociados al punto ECA', related_name='puntos_eca_inventario', to='inventory.inventario'),
        ),
        migrations.AlterField(
            model_name='puntoeca',
            name='telefono_punto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del punto ECA (único y validado sobre formato específico)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono fijo debe tener el formato 60 + indicativo + 7 dígitos (ej: 6012345678)', regex='^60\\d{8}')], verbose_name='Teléfono punto'),
        ),
    ]
