# Generated by Django 6.0.2 on 2026-06-01 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0012_alter_puntoeca_gestor_eca_alter_puntoeca_inventarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoeca',
            name='telefono_punto',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del punto ECA (único y validado sobre formato específico)', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono fijo debe tener el formato 60 + indicativo + 7 dígitos (ej: 6012345678)', regex='^60\\d{8}')], verbose_name='Teléfono punto'),
        ),
    ]
