# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0013_alter_puntoeca_telefono_punto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centroacopio',
            table='ecas_centro_acopio',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='ecas_localidad',
        ),
        migrations.AlterModelTable(
            name='puntoeca',
            table='ecas_punto_eca',
        ),
    ]
