# Generated by Django 6.0.2 on 2026-06-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0014_alter_centroacopio_table_alter_localidad_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntoeca',
            old_name='visible_en_mapa',
            new_name='es_visible_en_mapa',
        ),
    ]
