# Generated by Django 6.0.2 on 2026-06-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecas', '0016_puntoecafavorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroacopio',
            name='horario_atencion',
            field=models.CharField(blank=True, default='', help_text='Horario de atención al público, ej: L-V 8am-6pm', max_length=100),
        ),
        migrations.AlterField(
            model_name='centroacopio',
            name='sitio_web',
            field=models.CharField(blank=True, default='', help_text='URL del sitio web oficial, si aplica.', max_length=255),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='puntoeca',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Descripción detallada del punto ECA', max_length=500, verbose_name='Descripción del punto ECA'),
        ),
        migrations.AlterField(
            model_name='puntoeca',
            name='horario_atencion',
            field=models.CharField(blank=True, default='', help_text='Horario de atención al público, ej: L-V 8am-6pm', max_length=100),
        ),
        migrations.AlterField(
            model_name='puntoeca',
            name='sitio_web',
            field=models.CharField(blank=True, default='', help_text='URL del sitio web oficial, si aplica.', max_length=255),
        ),
    ]
