@startuml
skinparam actorStyle awesome
left to right direction

actor "Ciudadano" as UserC

package "Sistema InfoRecicla: Módulo de Exploración" {
    usecase "CU-03: Consultar Detalle de Punto ECA" as UC_Detail
    
    usecase "CU-03.1: Renderizar Información Base (Nombre, Dirección)" as UC_Base
    usecase "CU-03.2: Consultar Horarios y Estado Operativo" as UC_Time
    usecase "CU-03.3: Listar Materiales Aceptados y Precios" as UC_Mat
    
    usecase "EXT-19: Mostrar Alerta Visual - ECA Fuera de Servicio / Cerrado" as UC_Closed
}

' Relación del Actor Principal
UserC --> UC_Detail

' Relaciones de Inclusión (La vista de detalle requiere consolidar todos estos datos)
UC_Detail ..> UC_Base : <<include>>
UC_Detail ..> UC_Time : <<include>>
UC_Detail ..> UC_Mat : <<include>>

' Relaciones de Extensión (Condiciones dinámicas basadas en el estado o acción del usuario)
UC_Time <.. UC_Closed : <<extend>>

@enduml
