# Generated by Django 6.0.2 on 2026-03-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriapublicacion',
            table='categoria_publicacion',
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='comentario',
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='publicacion',
        ),
        migrations.AlterModelTable(
            name='reaccion',
            table='reacciones',
        ),
    ]
