# Generated by Django 6.0.2 on 2026-03-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_categoriapublicacion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
