# Generated by Django 6.0.2 on 2026-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_categoriapublicacion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(blank=True, help_text='Contenido principal de la publicación', null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la publicación', null=True, upload_to='publicaciones/'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='url_video',
            field=models.URLField(blank=True, help_text='URL del video (ej: YouTube, Vimeo)', null=True),
        ),
    ]
