# Generated by Django 6.0.3 on 2026-04-03 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_contenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapublicacion',
            name='tipo',
            field=models.CharField(choices=[('Punto Eca', 'Punto Eca'), ('Noticia', 'Noticia'), ('Evento', 'Evento'), ('Educativo', 'Educacion')], default='Noticia', max_length=30),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo',
            field=models.CharField(choices=[('Punto Eca', 'Punto Eca'), ('Noticia', 'Noticia'), ('Evento', 'Evento'), ('Educativo', 'Educacion')], default='Noticia', max_length=30),
        ),
        migrations.CreateModel(
            name='Guardados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, choices=[('Punto Eca', 'Punto Eca'), ('Noticia', 'Noticia'), ('Evento', 'Evento'), ('Educativo', 'Educacion')], max_length=15, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardado',
                'verbose_name_plural': 'Guardados',
                'db_table': 'tb_guardados',
                'abstract': False,
            },
        ),
    ]
