# Generated by Django 6.0.3 on 2026-04-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0005_guardados_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/videos/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/thumbnails/', verbose_name='Miniatura del video'),
        ),
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicaciones/imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publicaciones.publicacion')),
            ],
            options={
                'db_table': 'imagen_publicacion',
            },
        ),
    ]
