# Generated by Django 6.0.3 on 2026-06-06 03:23

import apps.core.upload_validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_categoriapublicacion_nombre_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenpublicacion',
            name='imagen',
            field=models.ImageField(upload_to='publicaciones/imagenes/', validators=[apps.core.upload_validators.MimeTypeValidator(['image/jpeg', 'image/png', 'image/webp'], 'La imagen'), apps.core.upload_validators.MaxFileSizeValidator(6291456, 'La imagen')]),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='publicaciones/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg']), apps.core.upload_validators.MimeTypeValidator(['video/mp4', 'video/webm', 'video/ogg'], 'El video'), apps.core.upload_validators.MaxFileSizeValidator(104857600, 'El video')], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/thumbnails/', validators=[apps.core.upload_validators.MimeTypeValidator(['image/jpeg', 'image/png', 'image/webp'], 'La miniatura del video'), apps.core.upload_validators.MaxFileSizeValidator(6291456, 'La miniatura del video')], verbose_name='Miniatura del video'),
        ),
    ]
