# Generated by Django 6.0.2 on 2026-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0007_categoriapublicacion_nombre_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar esta publicación en lugares destacados', verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='resumen',
            field=models.TextField(blank=True, help_text='Resumen corto para vistas previas (máx. 500 caracteres)', max_length=500, null=True, verbose_name='Resumen'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='video_url',
            field=models.URLField(blank=True, help_text='Pega el enlace de un video de YouTube, Vimeo, etc.', null=True, verbose_name='URL del video (YouTube, Vimeo...)'),
        ),
    ]
