# Generated by Django 6.0.2 on 2026-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0008_publicacion_destacado_publicacion_resumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='resumen',
            field=models.TextField(default='', help_text='Resumen corto para vistas previas (máx. 500 caracteres)', max_length=500, verbose_name='Resumen'),
        ),
    ]
