# Generated by Django 6.0.2 on 2026-06-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_options_alter_chat_ciudadano_and_more'),
        ('publicaciones', '0008_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='chat.mensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='publicaciones.publicacion'),
        ),
    ]
