# Generated by Django 6.0.2 on 2026-06-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventario_umbral_alerta_and_more'),
        ('publicaciones', '0009_notificacion_mensaje_alter_notificacion_publicacion'),
        ('scheduling', '0004_alter_evento_titulo_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='evento_instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='scheduling.eventoinstancia'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='inventory.inventario'),
        ),
    ]
