# Generated by Django 6.0.2 on 2026-06-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0009_alter_publicacion_resumen'),
        ('publicaciones', '0010_notificacion_evento_instancia_and_more'),
    ]

    operations = [
    ]
