# Generated by Django 6.0.2 on 2026-06-10 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_merge_20260609_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('BLOQUEADO', 'BLOQUEADO')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de publicación',
                'verbose_name_plural': 'Tipos de publicación',
                'db_table': 'tipo_publicacion',
                'abstract': False,
            },
        ),
    ]
