# Generated by Django 6.0.2 on 2026-06-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0011_merge_20260608_1914'),
        ('publicaciones', '0012_tipopublicacion'),
    ]

    operations = [
    ]
