# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0013_merge_0011_merge_20260608_1914_0012_tipopublicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapublicacion',
            options={'verbose_name': 'Categoría de publicación', 'verbose_name_plural': 'Categorías de publicación'},
        ),
        migrations.AlterModelOptions(
            name='imagenpublicacion',
            options={'verbose_name': 'Imagen de publicación', 'verbose_name_plural': 'Imágenes de publicación'},
        ),
        migrations.AlterUniqueTogether(
            name='guardados',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='guardados',
            constraint=models.UniqueConstraint(fields=('usuario', 'publicacion'), name='unique_usuario_publicacion_guardado'),
        ),
        migrations.AlterModelTable(
            name='categoriapublicacion',
            table='pub_categoria_publicacion',
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='pub_comentario',
        ),
        migrations.AlterModelTable(
            name='guardados',
            table='pub_guardado',
        ),
        migrations.AlterModelTable(
            name='imagenpublicacion',
            table='pub_imagen_publicacion',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='pub_notificacion',
        ),
        migrations.AlterModelTable(
            name='publicacion',
            table='pub_publicacion',
        ),
        migrations.AlterModelTable(
            name='reaccion',
            table='pub_reaccion',
        ),
        migrations.AlterModelTable(
            name='tipopublicacion',
            table='pub_tipo_publicacion',
        ),
    ]
