# Generated by Django 6.0.2 on 2026-06-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0014_alter_categoriapublicacion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='leido',
            new_name='es_leido',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='destacado',
            new_name='es_destacado',
        ),
    ]
