# Generated by Django 6.0.2 on 2026-06-26 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0017_remove_null_valor_reaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapublicacion',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='imagenpublicacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reaccion',
            name='valor',
            field=models.CharField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tipopublicacion',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
