# Generated by Django 6.0.2 on 2026-07-02 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0018_alter_categoriapublicacion_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoriapublicacion',
            constraint=models.UniqueConstraint(fields=('nombre', 'tipo'), name='uq_categoria_publicacion_nombre_tipo'),
        ),
        migrations.AddConstraint(
            model_name='publicacion',
            constraint=models.UniqueConstraint(fields=('titulo',), name='uq_publicacion_titulo'),
        ),
        migrations.AddConstraint(
            model_name='tipopublicacion',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_tipo_publicacion_nombre'),
        ),
    ]
