# Generated by Django 6.0.2 on 2026-06-01 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_editado_to_mensaje'),
        ('ecas', '0011_puntoeca_visible_en_mapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Chat punto-ciudadano'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='ciudadano',
            field=models.ForeignKey(help_text='Ciudadano participante (usuario autenticado)', on_delete=django.db.models.deletion.CASCADE, related_name='chats_ciudadano', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de inicio del chat.'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='punto',
            field=models.ForeignKey(help_text='Punto ECA asociado a esta conversación.', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='ecas.puntoeca'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(help_text='Chat al que pertenece este mensaje.', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='editado',
            field=models.BooleanField(default=False, help_text='Indica si el mensaje fue editado luego de enviado.'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='enviado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha/hora de envío.'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(default=False, help_text='True si el mensaje fue leído por el destinatario.'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(help_text='Usuario que envía el mensaje (puede ser PuntoECA o ciudadano).', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(help_text='Contenido del mensaje.'),
        ),
    ]
