# Generated by Django 6.0.2 on 2026-06-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_options_alter_chat_ciudadano_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['enviado_en'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chat_conversacion',
        ),
        migrations.AlterModelTable(
            name='mensaje',
            table='chat_mensaje',
        ),
    ]
