# Generated by Django 6.0.2 on 2026-06-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_options_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha_envio'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='editado',
            new_name='es_editado',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='leido',
            new_name='es_leido',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='enviado_en',
            new_name='fecha_envio',
        ),
    ]
